/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedBillsRouteImport } from './routes/_authenticated/bills'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedInvestmentsRouteImport } from './routes/_authenticated/investments'
import { Route as AuthenticatedReconciliationRouteImport } from './routes/_authenticated/reconciliation'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTaxesRouteImport } from './routes/_authenticated/taxes'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiDocumentsRouteImport } from './routes/api/documents'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiInvestmentRadarRouteImport } from './routes/api/investment-radar'
import { Route as ApiInvestmentRadarDailyRouteImport } from './routes/api/investment-radar-daily'
import { Route as ApiTransactionsRouteImport } from './routes/api/transactions'
import { Route as AuthenticatedWalletIndexRouteImport } from './routes/_authenticated/wallet/index'
import { Route as AuthenticatedWalletAccountsRouteImport } from './routes/_authenticated/wallet/accounts'
import { Route as AuthenticatedWalletConnectRouteImport } from './routes/_authenticated/wallet/connect'
import { Route as AuthenticatedWalletImportsRouteImport } from './routes/_authenticated/wallet/imports'
import { Route as ApiLedgerBalancesRouteImport } from './routes/api/ledger.balances'
import { Route as ApiTransactionsSummaryRouteImport } from './routes/api/transactions.summary'
import { Route as ApiWebhooksOpenfinanceProviderRouteImport } from './routes/api/webhooks/openfinance/$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillsRoute = AuthenticatedBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestmentsRoute =
  AuthenticatedInvestmentsRouteImport.update({
    id: '/investments',
    path: '/investments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReconciliationRoute =
  AuthenticatedReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaxesRoute = AuthenticatedTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsRoute = ApiDocumentsRouteImport.update({
  id: '/api/documents',
  path: '/api/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvestmentRadarRoute = ApiInvestmentRadarRouteImport.update({
  id: '/api/investment-radar',
  path: '/api/investment-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvestmentRadarDailyRoute = ApiInvestmentRadarDailyRouteImport.update({
  id: '/api/investment-radar-daily',
  path: '/api/investment-radar-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsRoute = ApiTransactionsRouteImport.update({
  id: '/api/transactions',
  path: '/api/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletIndexRoute =
  AuthenticatedWalletIndexRouteImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletAccountsRoute =
  AuthenticatedWalletAccountsRouteImport.update({
    id: '/wallet/accounts',
    path: '/wallet/accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletConnectRoute =
  AuthenticatedWalletConnectRouteImport.update({
    id: '/wallet/connect',
    path: '/wallet/connect',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletImportsRoute =
  AuthenticatedWalletImportsRouteImport.update({
    id: '/wallet/imports',
    path: '/wallet/imports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiLedgerBalancesRoute = ApiLedgerBalancesRouteImport.update({
  id: '/api/ledger/balances',
  path: '/api/ledger/balances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsSummaryRoute = ApiTransactionsSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ApiTransactionsRoute,
} as any)
const ApiWebhooksOpenfinanceProviderRoute =
  ApiWebhooksOpenfinanceProviderRouteImport.update({
    id: '/api/webhooks/openfinance/$provider',
    path: '/api/webhooks/openfinance/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/investments': typeof AuthenticatedInvestmentsRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/taxes': typeof AuthenticatedTaxesRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/investment-radar': typeof ApiInvestmentRadarRoute
  '/api/investment-radar-daily': typeof ApiInvestmentRadarDailyRoute
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/wallet/accounts': typeof AuthenticatedWalletAccountsRoute
  '/wallet/connect': typeof AuthenticatedWalletConnectRoute
  '/wallet/imports': typeof AuthenticatedWalletImportsRoute
  '/api/ledger/balances': typeof ApiLedgerBalancesRoute
  '/api/transactions/summary': typeof ApiTransactionsSummaryRoute
  '/wallet/': typeof AuthenticatedWalletIndexRoute
  '/api/webhooks/openfinance/$provider': typeof ApiWebhooksOpenfinanceProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/investments': typeof AuthenticatedInvestmentsRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/taxes': typeof AuthenticatedTaxesRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/investment-radar': typeof ApiInvestmentRadarRoute
  '/api/investment-radar-daily': typeof ApiInvestmentRadarDailyRoute
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/wallet/accounts': typeof AuthenticatedWalletAccountsRoute
  '/wallet/connect': typeof AuthenticatedWalletConnectRoute
  '/wallet/imports': typeof AuthenticatedWalletImportsRoute
  '/api/ledger/balances': typeof ApiLedgerBalancesRoute
  '/api/transactions/summary': typeof ApiTransactionsSummaryRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
  '/api/webhooks/openfinance/$provider': typeof ApiWebhooksOpenfinanceProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/bills': typeof AuthenticatedBillsRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/investments': typeof AuthenticatedInvestmentsRoute
  '/_authenticated/reconciliation': typeof AuthenticatedReconciliationRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/taxes': typeof AuthenticatedTaxesRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/investment-radar': typeof ApiInvestmentRadarRoute
  '/api/investment-radar-daily': typeof ApiInvestmentRadarDailyRoute
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/_authenticated/wallet/accounts': typeof AuthenticatedWalletAccountsRoute
  '/_authenticated/wallet/connect': typeof AuthenticatedWalletConnectRoute
  '/_authenticated/wallet/imports': typeof AuthenticatedWalletImportsRoute
  '/api/ledger/balances': typeof ApiLedgerBalancesRoute
  '/api/transactions/summary': typeof ApiTransactionsSummaryRoute
  '/_authenticated/wallet/': typeof AuthenticatedWalletIndexRoute
  '/api/webhooks/openfinance/$provider': typeof ApiWebhooksOpenfinanceProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agent'
    | '/bills'
    | '/budget'
    | '/dashboard'
    | '/goals'
    | '/insights'
    | '/investments'
    | '/reconciliation'
    | '/reports'
    | '/security'
    | '/settings'
    | '/taxes'
    | '/transactions'
    | '/api/chat'
    | '/api/documents'
    | '/api/health'
    | '/api/investment-radar'
    | '/api/investment-radar-daily'
    | '/api/transactions'
    | '/wallet/accounts'
    | '/wallet/connect'
    | '/wallet/imports'
    | '/api/ledger/balances'
    | '/api/transactions/summary'
    | '/wallet/'
    | '/api/webhooks/openfinance/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agent'
    | '/bills'
    | '/budget'
    | '/dashboard'
    | '/goals'
    | '/insights'
    | '/investments'
    | '/reconciliation'
    | '/reports'
    | '/security'
    | '/settings'
    | '/taxes'
    | '/transactions'
    | '/api/chat'
    | '/api/documents'
    | '/api/health'
    | '/api/investment-radar'
    | '/api/investment-radar-daily'
    | '/api/transactions'
    | '/wallet/accounts'
    | '/wallet/connect'
    | '/wallet/imports'
    | '/api/ledger/balances'
    | '/api/transactions/summary'
    | '/wallet'
    | '/api/webhooks/openfinance/$provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agent'
    | '/_authenticated/bills'
    | '/_authenticated/budget'
    | '/_authenticated/dashboard'
    | '/_authenticated/goals'
    | '/_authenticated/insights'
    | '/_authenticated/investments'
    | '/_authenticated/reconciliation'
    | '/_authenticated/reports'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/taxes'
    | '/_authenticated/transactions'
    | '/api/chat'
    | '/api/documents'
    | '/api/health'
    | '/api/investment-radar'
    | '/api/investment-radar-daily'
    | '/api/transactions'
    | '/_authenticated/wallet/accounts'
    | '/_authenticated/wallet/connect'
    | '/_authenticated/wallet/imports'
    | '/api/ledger/balances'
    | '/api/transactions/summary'
    | '/_authenticated/wallet/'
    | '/api/webhooks/openfinance/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDocumentsRoute: typeof ApiDocumentsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInvestmentRadarRoute: typeof ApiInvestmentRadarRoute
  ApiInvestmentRadarDailyRoute: typeof ApiInvestmentRadarDailyRoute
  ApiTransactionsRoute: typeof ApiTransactionsRouteWithChildren
  ApiLedgerBalancesRoute: typeof ApiLedgerBalancesRoute
  ApiWebhooksOpenfinanceProviderRoute: typeof ApiWebhooksOpenfinanceProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bills': {
      id: '/_authenticated/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthenticatedBillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investments': {
      id: '/_authenticated/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AuthenticatedInvestmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reconciliation': {
      id: '/_authenticated/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AuthenticatedReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taxes': {
      id: '/_authenticated/taxes'
      path: '/taxes'
      fullPath: '/taxes'
      preLoaderRoute: typeof AuthenticatedTaxesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents': {
      id: '/api/documents'
      path: '/api/documents'
      fullPath: '/api/documents'
      preLoaderRoute: typeof ApiDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/investment-radar': {
      id: '/api/investment-radar'
      path: '/api/investment-radar'
      fullPath: '/api/investment-radar'
      preLoaderRoute: typeof ApiInvestmentRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/investment-radar-daily': {
      id: '/api/investment-radar-daily'
      path: '/api/investment-radar-daily'
      fullPath: '/api/investment-radar-daily'
      preLoaderRoute: typeof ApiInvestmentRadarDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions': {
      id: '/api/transactions'
      path: '/api/transactions'
      fullPath: '/api/transactions'
      preLoaderRoute: typeof ApiTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet/': {
      id: '/_authenticated/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof AuthenticatedWalletIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet/accounts': {
      id: '/_authenticated/wallet/accounts'
      path: '/wallet/accounts'
      fullPath: '/wallet/accounts'
      preLoaderRoute: typeof AuthenticatedWalletAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet/connect': {
      id: '/_authenticated/wallet/connect'
      path: '/wallet/connect'
      fullPath: '/wallet/connect'
      preLoaderRoute: typeof AuthenticatedWalletConnectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet/imports': {
      id: '/_authenticated/wallet/imports'
      path: '/wallet/imports'
      fullPath: '/wallet/imports'
      preLoaderRoute: typeof AuthenticatedWalletImportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ledger/balances': {
      id: '/api/ledger/balances'
      path: '/api/ledger/balances'
      fullPath: '/api/ledger/balances'
      preLoaderRoute: typeof ApiLedgerBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/summary': {
      id: '/api/transactions/summary'
      path: '/summary'
      fullPath: '/api/transactions/summary'
      preLoaderRoute: typeof ApiTransactionsSummaryRouteImport
      parentRoute: typeof ApiTransactionsRoute
    }
    '/api/webhooks/openfinance/$provider': {
      id: '/api/webhooks/openfinance/$provider'
      path: '/api/webhooks/openfinance/$provider'
      fullPath: '/api/webhooks/openfinance/$provider'
      preLoaderRoute: typeof ApiWebhooksOpenfinanceProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedBillsRoute: typeof AuthenticatedBillsRoute
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedInvestmentsRoute: typeof AuthenticatedInvestmentsRoute
  AuthenticatedReconciliationRoute: typeof AuthenticatedReconciliationRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTaxesRoute: typeof AuthenticatedTaxesRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedWalletAccountsRoute: typeof AuthenticatedWalletAccountsRoute
  AuthenticatedWalletConnectRoute: typeof AuthenticatedWalletConnectRoute
  AuthenticatedWalletImportsRoute: typeof AuthenticatedWalletImportsRoute
  AuthenticatedWalletIndexRoute: typeof AuthenticatedWalletIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedBillsRoute: AuthenticatedBillsRoute,
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedInvestmentsRoute: AuthenticatedInvestmentsRoute,
  AuthenticatedReconciliationRoute: AuthenticatedReconciliationRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTaxesRoute: AuthenticatedTaxesRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedWalletAccountsRoute: AuthenticatedWalletAccountsRoute,
  AuthenticatedWalletConnectRoute: AuthenticatedWalletConnectRoute,
  AuthenticatedWalletImportsRoute: AuthenticatedWalletImportsRoute,
  AuthenticatedWalletIndexRoute: AuthenticatedWalletIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiTransactionsRouteChildren {
  ApiTransactionsSummaryRoute: typeof ApiTransactionsSummaryRoute
}

const ApiTransactionsRouteChildren: ApiTransactionsRouteChildren = {
  ApiTransactionsSummaryRoute: ApiTransactionsSummaryRoute,
}

const ApiTransactionsRouteWithChildren = ApiTransactionsRoute._addFileChildren(
  ApiTransactionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDocumentsRoute: ApiDocumentsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInvestmentRadarRoute: ApiInvestmentRadarRoute,
  ApiInvestmentRadarDailyRoute: ApiInvestmentRadarDailyRoute,
  ApiTransactionsRoute: ApiTransactionsRouteWithChildren,
  ApiLedgerBalancesRoute: ApiLedgerBalancesRoute,
  ApiWebhooksOpenfinanceProviderRoute: ApiWebhooksOpenfinanceProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
